# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 580586170622b42982cda9e8d30d85f66fcb197af99ff1013d0601ea986894859d761ecb8ab48559fbacb61129c1f72626d95d6e2e4f1908014b319fcc988271

test:
  secret_key_base: 9ddaebd9f936dc865445db6b151ce35e6ed1372c413b55a7e2cc861840fa958704d8fa75ca7dae14d23066a741c79ce374936c63ae4a4e689ed71085d702da80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
